In [2]:
import tensorflow as tf

**tf.constant**

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


**tf.cast**

In [ ]:
tensor_one_d = tf.constant([2,0,-3, 8, 90], dtype=tf.float16) # memory  (Quantization)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)

print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_two_d.shape)

(4, 3)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d = tf.constant([
[
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]

],
[
    [[13,26,0],
    [3,5,-12]],

    [[10,2,0],
     [1,0,23]],

    [[5,8,0],
     [2,73,0]],

    [[2,1,9],
     [4,-30,32]]

],
[
    [[103,26,0],
    [3,50,-12]],

    [[10,2,0],
     [1,0,23]],

    [[5,8,0],
     [2,73,0]],

    [[2,1,9],
     [4,-30,32]]
]

])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5  -1]]

  [[ 10   2   0]
   [  1   0   2]]

  [[  5   8   0]
   [  2   7   0]]

  [[  2   1   9]
   [  4  -3  32]]]


 [[[ 13  26   0]
   [  3   5 -12]]

  [[ 10   2   0]
   [  1   0  23]]

  [[  5   8   0]
   [  2  73   0]]

  [[  2   1   9]
   [  4 -30  32]]]


 [[[103  26   0]
   [  3  50 -12]]

  [[ 10   2   0]
   [  1   0  23]]

  [[  5   8   0]
   [  2  73   0]]

  [[  2   1   9]
   [  4 -30  32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


**tf.eye**

In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(2, 4, 5, 3), dtype=float32)


**tf.fill**

In [ ]:
filled_tensor = tf.fill([2,3], 9)
filled_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

**tf.ones**

In [ ]:
tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

**tf.ones_like**

In [ ]:
tf.ones_like(
    filled_tensor
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [ ]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


**tf.rank**


https://m.blog.naver.com/sw4r/221416614473

In [ ]:
tf.rank(tensor_three_d) # 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

**tf.size**

In [ ]:
tf.size(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

**random.normal/uniform**

In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None
) #from normal distribution

In [ ]:
random_tensor = tf.random.uniform(
    [1,],
    minval=0,
    maxval=None, #default is 1
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
) # from uniform distribution

**tf.random.set_seed**

In [ ]:
# for reproducibility
tf.random.set_seed(10)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([3 4 2], shape=(3,), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([0 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
# for reproducibility
tf.random.set_seed(10)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([3 4 2], shape=(3,), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([0 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


## Indexing

In [4]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:5+1:2])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)


In [7]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
# print(tensor_two_d[:3,:2])
print(tensor_two_d[2,1:])

tf.Tensor([5 6], shape=(2,), dtype=int32)


In [11]:
print(tensor_two_d[:,1])
print(tensor_two_d[...,1]) # pick up all the rows

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [12]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]

])
print(tensor_three_d[0,:,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [14]:
print(tensor_three_d[0,:,-1])

tf.Tensor([ 0 -1], shape=(2,), dtype=int32)


In [19]:
print(tensor_three_d[...,:,2]) # multiple ... not allowed

tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)
