https://www.tensorflow.org/api_docs/python/tf/linalg

In [ ]:
import tensorflow as tf

### tf.linalg.matmul

In [ ]:
x_1 = tf.constant([[1,2,0],
                   [3,5,1]])
x_2 = tf.constant([[1,2,0,2],
                  [3,5,-1,2],
                  [4,5,6,0]])

print(x_1.shape)
print(x_2.shape)

tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

(2, 3)
(3, 4)


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 7, 12, -2,  6],
       [22, 36,  1, 16]], dtype=int32)>

In [ ]:
print(x_1@x_2) # matrix multiplication (* for element-wise)

tf.Tensor(
[[ 7 12 -2  6]
 [22 36  1 16]], shape=(2, 4), dtype=int32)


Transpose

In [ ]:
# transpose
x_1 = tf.constant([[1,2,0]])
print(x_1.shape)

tf.transpose(x_1)
print(tf.transpose(x_1))

(1, 3)
tf.Tensor(
[[1]
 [2]
 [0]], shape=(3, 1), dtype=int32)


In [ ]:
x_1 = tf.constant([[1,2,0]])
x_2 = tf.constant([[1,2,0,2],
                  [3,5,-1,2],
                  [4,5,6,0]])
x_3 = tf.constant([[1,2,0,2],
                  [3,5,-1,2]])

print(x_1.shape)
print(x_2.shape) #(3,4)
print(x_3.shape) #(2,4)

# These are same
print(x_2@tf.transpose(x_3))
print(tf.linalg.matmul(
    x_2,
    x_3,
    transpose_a=False,
    transpose_b=True,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
))

(1, 3)
(3, 4)
(2, 4)
tf.Tensor(
[[ 9 17]
 [17 39]
 [14 31]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 9 17]
 [17 39]
 [14 31]], shape=(3, 2), dtype=int32)


In [ ]:
x_2.T ## EagerTensor Error?

In [ ]:
## for 3d tensor
x_1 = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]

])

print(x_1.shape)

x_2 = tf.constant([
    [[5,1,4],
    [34,15,1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]

])

print(x_2.shape)

(4, 2, 3)
(4, 2, 3)


Matmul in batch

In [ ]:
# When matmul is done in batches, look at each batch and do matmul
# make sure each batches are multipliable
# batch is the one in axis 0
tf.linalg.matmul(x_1, x_2)

# Currently, (2,3)@(2,3) incompatible

In [ ]:
x_1 = tf.constant([
    [[1,2],
    [3,5]],

    [[10,2],
     [1,0]],

    [[5,8],
     [2,7]],

    [[2,1],
     [4,-3]]

])

print(x_1.shape)

x_2 = tf.constant([
    [[5,1,4],
    [34,15,1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]

])
print(x_2.shape)

(4, 2, 2)
(4, 2, 3)


In [ ]:
# (2,2)@(2,3) is compatible
tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 73,  31,   6],
        [185,  78,  17]],

       [[102,  20,   4],
        [ 10,   2,   0]],

       [[ 41,  96,   0],
        [ 24,  65,   0]],

       [[  8,  -1,  50],
        [ -4,  13, -60]]], dtype=int32)>

Sparse tensors

In [ ]:
# There will be many cased when tensors are mostly made of zeros.
x_1 = tf.constant([[0,0],
                  [0,2]])
x_2 = tf.constant([[1,0,0],
                   [0,0,0]])

print(tf.linalg.matmul(x_1, x_2, a_is_sparse=True, b_is_sparse=True))
# Faster operation by telling it's sparse matrix

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


### tf.linalg.band_part

Copy a tensor setting everything outside a central band in each innermost matrix to zero.

In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype=tf.float16)

## in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper)
## m - rows, n - columns

tf.linalg.band_part(tensor_two_d, 0, 0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [ ]:
## m - rows, n - columns
# The results of m-n and n-m in matrix
# m-n (row idx - column idx)
tensor_two_d_m_n = tf.constant([[0, -1, -2],
                                [1, 0, -1],
                                [2, 1, 0],
                                [3, 2, 1]], dtype=tf.float16)

# n-m
tensor_two_d_n_m = tf.constant([[ 0,  1, 2],
                                [-1,  0,  1],
                                [-2, -1,  0],
                                [-3, -2, -1]], dtype=tf.float16)

In [ ]:
# How band part is calculated
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype=tf.float16)

tf.linalg.band_part(tensor_two_d, 0, 0)
# lower = 0
# upper = 0
# (m-n <= lower) && (n-m <= upper)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

Special use cases
- tf.linalg.band_part(input, 0, -1) ==> Upper triangular part.
- tf.linalg.band_part(input, -1, 0) ==> Lower triangular part.
- tf.linalg.band_part(input, 0, 0) ==> Diagonal.

In [ ]:
tf.linalg.band_part(tensor_two_d, 0, -1)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [ ]:
tf.linalg.band_part(tensor_two_d, -1, 0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [3., 5., 0.],
       [1., 5., 6.],
       [2., 3., 8.]], dtype=float16)>

### tf.linalg.inv

Computes the inverse of one or more square invertible matrices or their adjoints

In [ ]:
# Should be sqaure matrix
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype=tf.float32) # float16 causes error

tensor_two_d_inv = tf.linalg.inv(tensor_two_d)
tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.7413249 , -0.01892742,  0.3154574 ],
       [-0.12933755, -0.00946371,  0.1577287 ],
       [-0.01577287,  0.01104101, -0.01735016]], dtype=float32)>

In [ ]:
tensor_two_d@tensor_two_d_inv # identity matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  7.4505806e-09,  0.0000000e+00],
       [ 1.6391277e-07,  1.0000000e+00,  4.4703484e-08],
       [-5.2154064e-08,  7.4505806e-08,  1.0000000e+00]], dtype=float32)>

### tf.linalg.svd

In [ ]:
# a is a tensor.
# s is a tensor of singular values.
# u is a tensor of left singular vectors.
# v is a tensor of right singular vectors.

s, u, v = tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03044816  0.07330841  0.99684453]
 [ 0.0528536   0.9957936  -0.07484547]
 [ 0.998138   -0.05496572 -0.02644547]], shape=(3, 3), dtype=float32)


In [ ]:
""