https://www.tensorflow.org/api_docs/python/tf/linalg

In [2]:
import tensorflow as tf

### tf.linalg.matmul

In [5]:
x_1 = tf.constant([[1,2,0],
                   [3,5,1]])
x_2 = tf.constant([[1,2,0,2],
                  [3,5,-1,2],
                  [4,5,6,0]])

print(x_1.shape)
print(x_2.shape)

tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

(2, 3)
(3, 4)


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 7, 12, -2,  6],
       [22, 36,  1, 16]], dtype=int32)>

In [9]:
print(x_1@x_2) # matrix multiplication (* for element-wise)

tf.Tensor(
[[ 7 12 -2  6]
 [22 36  1 16]], shape=(2, 4), dtype=int32)


Transpose

In [14]:
# transpose
x_1 = tf.constant([[1,2,0]])
print(x_1.shape)

tf.transpose(x_1)
print(tf.transpose(x_1))

(1, 3)
tf.Tensor(
[[1]
 [2]
 [0]], shape=(3, 1), dtype=int32)


In [19]:
x_1 = tf.constant([[1,2,0]])
x_2 = tf.constant([[1,2,0,2],
                  [3,5,-1,2],
                  [4,5,6,0]])
x_3 = tf.constant([[1,2,0,2],
                  [3,5,-1,2]])

print(x_1.shape)
print(x_2.shape) #(3,4)
print(x_3.shape) #(2,4)

# These are same
print(x_2@tf.transpose(x_3))
print(tf.linalg.matmul(
    x_2,
    x_3,
    transpose_a=False,
    transpose_b=True,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
))

(1, 3)
(3, 4)
(2, 4)
tf.Tensor(
[[ 9 17]
 [17 39]
 [14 31]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 9 17]
 [17 39]
 [14 31]], shape=(3, 2), dtype=int32)


In [ ]:
x_2.T ## EagerTensor Error?

In [22]:
## for 3d tensor
x_1 = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]

])

print(x_1.shape)

x_2 = tf.constant([
    [[5,1,4],
    [34,15,1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]

])

print(x_2.shape)

(4, 2, 3)
(4, 2, 3)


Matmul in batch

In [ ]:
# When matmul is done in batches, look at each batch and do matmul
# make sure each batches are multipliable
# batch is the one in axis 0
tf.linalg.matmul(x_1, x_2)

# Currently, (2,3)@(2,3) incompatible

In [25]:
x_1 = tf.constant([
    [[1,2],
    [3,5]],

    [[10,2],
     [1,0]],

    [[5,8],
     [2,7]],

    [[2,1],
     [4,-3]]

])

print(x_1.shape)

x_2 = tf.constant([
    [[5,1,4],
    [34,15,1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]

])
print(x_2.shape)

(4, 2, 2)
(4, 2, 3)


In [26]:
# (2,2)@(2,3) is compatible
tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 73,  31,   6],
        [185,  78,  17]],

       [[102,  20,   4],
        [ 10,   2,   0]],

       [[ 41,  96,   0],
        [ 24,  65,   0]],

       [[  8,  -1,  50],
        [ -4,  13, -60]]], dtype=int32)>

Sparse tensors

In [30]:
# There will be many cased when tensors are mostly made of zeros.
x_1 = tf.constant([[0,0],
                  [0,2]])
x_2 = tf.constant([[1,0,0],
                   [0,0,0]])

print(tf.linalg.matmul(x_1, x_2, a_is_sparse=True, b_is_sparse=True))
# Faster operation by telling it's sparse matrix

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


### tf.linalg.band_part