https://www.tensorflow.org/api_docs/python/tf/math

In [2]:
import tensorflow as tf

### tf.abs

In [3]:
# Absolute value
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [4]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.2>

In [5]:
# Absolute number of complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [7]:
print(tf.abs(tf.constant([-2.25 + 4.75j])))
print(tf.sqrt((-2.25)**2 + 4.75**2))

tf.Tensor([5.25594901], shape=(1,), dtype=float64)
tf.Tensor(5.255949, shape=(), dtype=float32)


### tf.{add, multiply, divide, math.divide_no_nan}

In [9]:
# element-wise addition
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,0,11], dtype=tf.int32)

print(tf.add(x_1, x_2))

tf.Tensor([12  9  8 12  4 17], shape=(6,), dtype=int32)


In [10]:
# if divided by zero
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,0,11], dtype=tf.int32)

tf.divide(x_1, x_2) # inf

<tf.Tensor: shape=(6,), dtype=float64, numpy=
array([0.71428571, 0.5       , 3.        , 1.        ,        inf,
       0.54545455])>

In [11]:
# using divide_no_nan
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.float32) # should be float
x_2 = tf.constant([7,6,2,6,0,11], dtype=tf.float32)

tf.math.divide_no_nan(x_1, x_2) # safe division

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.71428573, 0.5       , 3.        , 1.        , 0.        ,
       0.54545456], dtype=float32)>

In [15]:
# Broadcasting
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.float32)
x_2 = tf.constant([7], dtype=tf.float32)
x_2_stretched = tf.constant([7,7,7,7,7,7], dtype=tf.float32)


print(tf.add(x_1, x_2))
print(tf.add(x_1, x_2_stretched))

tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)
tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)


In [16]:
# how element-wise broadcasting works
# stretched
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.float32)
x_2 = tf.constant([[7],[5],[3]], dtype=tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

# [5,3,6,6,4,6] [7,7,7,7,7,7]
# [5,3,6,6,4,6] [5,5,5,5,5,5]
# [5,3,6,6,4,6] [3,3,3,3,3,3]

(6,)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


### tf.math.{maximum, minumum, argmax}

In [17]:
# position of maximum value
x_argmax = tf.constant([200, 20, 30, 3, 6])
tf.math.argmax(x_argmax)

(3, 5)


In [19]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                       [14, 45, 23, 5, 27]])
print(x_argmax.shape)

(3, 5)


In [21]:
tf.math.argmax(x_argmax, 0) # **fixing the axis 0**, and compare within column

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>

In [23]:
tf.math.argmin(x_argmax, 1) # fixing the axis 0, and compare within column

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 3, 3])>

### tf.math.equal

In [24]:
x = tf.constant([2, 4])
y = tf.constant(2) # broadcasting
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

### tf.math.pow

In [25]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.math.pow(x,y) # power of x to y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

### tf.math.reduce*

In [26]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False, name=None) # adding up (reducing into sum)

<tf.Tensor: shape=(), dtype=int32, numpy=35>

In [27]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

tf.math.reduce_max(tensor_two_d, axis=None, keepdims=False, name=None) # reducing into max value in the tensor

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [29]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

print(tensor_two_d.shape)
print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=False, name=None)) # fixing axis 0, summing axis 1(column)

(4, 3)
tf.Tensor([ 7 15 13], shape=(3,), dtype=int32)


In [31]:
print(tf.math.reduce_sum(tensor_two_d, axis=1, keepdims=False, name=None))

tf.Tensor([ 3  7 12 13], shape=(4,), dtype=int32)


In [32]:
print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False, name=None)) # make the tensor float to see accurate value

tf.Tensor([1 3 3], shape=(3,), dtype=int32)


### tf.math.sigmoid

In [33]:
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>

### tf.math.top_k

In [36]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

tf.math.top_k(tensor_two_d, k=1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [5],
       [6],
       [8]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)