https://www.tensorflow.org/api_docs/python/tf/Variable

In [ ]:
import tensorflow as tf

In [ ]:
x = tf.constant([1,2])
x_var = tf.Variable(x, name="var1")
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


assign: update in the variable

In [ ]:
v = tf.Variable(1.)
v.assign(2)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [ ]:
x_var.assign_sub([3,6])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -4], dtype=int32)>

assigning device to use

In [ ]:
with tf.device("GPU:0"):
  x_var_gpu = tf.Variable(0.2)

with tf.device("CPU:0"):
  x_var_cpu = tf.Variable(0.2)

print(x_var_gpu.device)
print(x_var_cpu.device)

/job:localhost/replica:0/task:0/device:GPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [ ]:
with tf.device("CPU:0"):
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])

with tf.device("GPU:0"):
  x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:GPU:0
